INSERT INTO `el_kelas` VALUES (1, 'KELAS X', NULL, 1, 1);
INSERT INTO `el_kelas` VALUES (2, 'KELAS X - A', 1, 2, 1);
INSERT INTO `el_kelas` VALUES (3, 'KELAS X - B', 1, 3, 1);
INSERT INTO `el_kelas` VALUES (4, 'KELAS X - C', 1, 4, 1);
INSERT INTO `el_kelas` VALUES (5, 'KELAS X - D', 1, 5, 1);
INSERT INTO `el_kelas` VALUES (6, 'KELAS XI', NULL, 6, 1);
INSERT INTO `el_kelas` VALUES (7, 'KELAS XI - IPA 1', 6, 7, 1);
INSERT INTO `el_kelas` VALUES (8, 'KELAS XI - IPA 2', 6, 8, 1);
INSERT INTO `el_kelas` VALUES (9, 'KELAS XI - IPS 1', 6, 9, 1);
INSERT INTO `el_kelas` VALUES (10, 'KELAS XI - IPS 2', 6, 10, 1);
INSERT INTO `el_kelas` VALUES (11, 'KELAS XII', NULL, 11, 1);
INSERT INTO `el_kelas` VALUES (12, 'KELAS XII - IPA 1', 11, 12, 1);
INSERT INTO `el_kelas` VALUES (13, 'KELAS XII - IPA 2', 11, 13, 1);
INSERT INTO `el_kelas` VALUES (14, 'KELAS XII - IPS 1', 11, 14, 1);
INSERT INTO `el_kelas` VALUES (15, 'KELAS XII - IPS 2', 11, 15, 1);
