INSERT INTO `el_pengaturan` VALUES ('email-server', 'Email server', 'dicky@domain.com');
INSERT INTO `el_pengaturan` VALUES ('email-template-approve-pengajar', 'Approve pengajar (email pengajar)', '{\"subject\":\"Pengaktifan Akun\",\"body\":\"<p>Hai {$nama},<\\/p>\\n<p>Anda telah diterima sebagai pengajar pada {$nama_sekolah}, berikut informasi data diri anda:<\\/p>\\n<p>{$tabel_profil}<\\/p>\\n<p>Anda dapat login ke sistem E-Learning menggunakan username dan password yang telah anda buat saat pendaftaran, login pada url berikut : {$url_login}<\\/p>\"}');
INSERT INTO `el_pengaturan` VALUES ('email-template-approve-siswa', 'Approve siswa (email siswa)', '{\"subject\":\"Pengaktifan Akun\",\"body\":\"<p>Hai {$nama},<\\/p>\\n<p>Anda telah diterima sebagai siswa pada {$nama_sekolah}, berikut informasi data diri anda:<\\/p>\\n<p>{$tabel_profil}<\\/p>\\n<p>Anda dapat login ke sistem E-Learning menggunakan username dan password yang telah anda buat saat pendaftaran, login pada url berikut : {$url_login}<\\/p>\"}');
INSERT INTO `el_pengaturan` VALUES ('email-template-link-reset', 'Link Reset Password', '{\"subject\":\"Reset Password\",\"body\":\"<p>Hai,<\\/p>\\n<p>Anda mengirimkan permintaan untuk reset password anda, klik link berikut untuk memulai reset password : {$link_reset}<\\/p>\"}');
INSERT INTO `el_pengaturan` VALUES ('email-template-register-pengajar', 'Register pengajar (email pengajar)', '{\"subject\":\"Registrasi Berhasil\",\"body\":\"<p>Hai {$nama},<\\/p>\\n<p>Terimakasih telah melakukan pendaftaran sebagai pengajar di E-Learning {$nama_sekolah}. Akun anda akan segera diaktifkan oleh admin.<\\/p>\"}');
INSERT INTO `el_pengaturan` VALUES ('email-template-register-siswa', 'Register siswa (email siswa)', '{\"subject\":\"Registrasi Berhasil\",\"body\":\"<p>Hai {$nama},<\\/p>\\n<p>Terimakasih telah melakukan pendaftaran sebagai siswa di E-Learning {$nama_sekolah}. Akun anda akan segera diaktifkan oleh admin.<\\/p>\"}');
INSERT INTO `el_pengaturan` VALUES ('info-registrasi', 'Info Registrasi', '<p>Silakan mendaftar sebagai siswa atau pengajar (jika anda sebagai pengajar) dengan memilih sesuai tab berikut :</p>\r\n');
INSERT INTO `el_pengaturan` VALUES ('peraturan-elearning', 'Peraturan E-learning', '');
INSERT INTO `el_pengaturan` VALUES ('registrasi-pengajar', 'Registrasi Pengajar', '1');
INSERT INTO `el_pengaturan` VALUES ('registrasi-siswa', 'Registrasi Siswa', '1');
INSERT INTO `el_pengaturan` VALUES ('versi', 'Versi', '2.0');
INSERT INTO `el_pengaturan` VALUES ('jenjang', 'jenjang', 'SMA');
INSERT INTO `el_pengaturan` VALUES ('nama-sekolah', 'nama-sekolah', 'SMA SINT CAROLUS BENGKULU');
INSERT INTO `el_pengaturan` VALUES ('alamat', 'alamat', 'Jalan Kapuas Raya no.22');
INSERT INTO `el_pengaturan` VALUES ('telp', 'telp', '081367783246');
INSERT INTO `el_pengaturan` VALUES ('install-success', 'install-success', '1');
INSERT INTO `el_pengaturan` VALUES ('status-registrasi-siswa', 'status-registrasi-siswa', '0');
INSERT INTO `el_pengaturan` VALUES ('status-registrasi-pengajar', 'status-registrasi-pengajar', '0');
INSERT INTO `el_pengaturan` VALUES ('smtp-host', 'smtp-host', '');
INSERT INTO `el_pengaturan` VALUES ('smtp-username', 'smtp-username', '');
INSERT INTO `el_pengaturan` VALUES ('smtp-pass', 'smtp-pass', '');
INSERT INTO `el_pengaturan` VALUES ('smtp-port', 'smtp-port', '');
INSERT INTO `el_pengaturan` VALUES ('edit-username-siswa', 'edit-username-siswa', '1');
INSERT INTO `el_pengaturan` VALUES ('edit-foto-siswa', 'edit-foto-siswa', '1');
INSERT INTO `el_pengaturan` VALUES ('info-slide-1', 'info-slide-1', '');
INSERT INTO `el_pengaturan` VALUES ('info-slide-2', 'info-slide-2', '');
INSERT INTO `el_pengaturan` VALUES ('info-slide-3', 'info-slide-3', '');
INSERT INTO `el_pengaturan` VALUES ('info-slide-4', 'info-slide-4', '');
INSERT INTO `el_pengaturan` VALUES ('logo-sekolah', 'logo-sekolah', 'logo-sekolah.jpeg');
